micronaut:
  application:
    name: helloWorld

  caches:
    mulkeys:
      maximumSize: 10000
    my-cache:
      maximumSize: 10000
    counter:
      maximumSize: 40
          
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          jwks:
            okta:
              url: 'https://mycompany.okta.com/oauth2/default/v1/keys'
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        access:
          - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3

# redisson:
#   single-server-config:
#      address: "redis://127.0.0.1:6379"
#   threads: 32
#   useScriptCache: true
#   netty-threads: 16

# nats.addresses:
# - nats://localhost:4222


datasources:
  default:
  #  url: jdbc:h2:mem:test;INIT=runscript from 'classpath:sql/create.sql';LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    url: jdbc:h2:tcp://localhost/~/test;CACHE_SIZE=30720;CACHE_TYPE=SOFT_LRU
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE
    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
    entity-scan:
      packages: 'hello.world'


ehcache:
  storage-path: /Users/yangyi/caches
  caches:
    a-cache:
      enabled: true
      heap:
        max-entries: 500
      offheap:
        max-entries: 5000
      disk:
        max-size: 10000000000   #10Gb

logger:
  levels:
    hello.world: INFO