micronaut:
  application:
    name: helloWorld
netty:
  default:
    allocator:
      max-order: 3

redisson:
  single-server-config:
     address: "redis://127.0.0.1:6379"
  threads: 32
  useScriptCache: true
  netty-threads: 16

nats.addresses:
- nats://localhost:4222